default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: democracy_development

test:
  <<: *default
  database: democracy_test

staging:
  <<: *default
  database: democracy_staging

production:
  <<: *default
  database: democracy_production
